// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.API.Model;

namespace Projekt.API.Migrations
{
    [DbContext(typeof(ProjektDbContext))]
    [Migration("20220409212658_bugs")]
    partial class bugs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIProjekt.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "prettyprincess@hotmail.com",
                            FirstName = "Yasmin",
                            LastName = "Larian",
                            Phone = "0701234567",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "angel@hotmail.com",
                            FirstName = "Cloe",
                            LastName = "Santon",
                            Phone = "0709876543",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "bunnyboo@hotmail.com",
                            FirstName = "Sasha",
                            LastName = "Mason",
                            Phone = "0729874934",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "koolkat@live.com",
                            FirstName = "Jade",
                            LastName = "Hunter",
                            Phone = "0701271244",
                            ProjectId = 1
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "barbie@hotmail.com",
                            FirstName = "Barbara",
                            LastName = "Roberts",
                            Phone = "0737485932",
                            ProjectId = 2
                        },
                        new
                        {
                            EmployeeId = 6,
                            Email = "chrissy@hotmail.com",
                            FirstName = "Christie",
                            LastName = "O'Neil",
                            Phone = "0767512409",
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("APIProjekt.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            ProjectName = "Bratz Dolls"
                        },
                        new
                        {
                            ProjectId = 2,
                            ProjectName = "Barbie Dolls"
                        });
                });

            modelBuilder.Entity("APIProjekt.Models.TimeReport", b =>
                {
                    b.Property<int>("TimeReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("TimeReportId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeReports");

                    b.HasData(
                        new
                        {
                            TimeReportId = 1,
                            EmployeeId = 1,
                            EndDate = new DateTime(2022, 1, 3, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 1
                        },
                        new
                        {
                            TimeReportId = 2,
                            EmployeeId = 2,
                            EndDate = new DateTime(2022, 1, 4, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 4, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Week = 1
                        },
                        new
                        {
                            TimeReportId = 3,
                            EmployeeId = 2,
                            EndDate = new DateTime(2022, 1, 5, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 1
                        },
                        new
                        {
                            TimeReportId = 4,
                            EmployeeId = 2,
                            EndDate = new DateTime(2022, 1, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 7, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Week = 1
                        },
                        new
                        {
                            TimeReportId = 5,
                            EmployeeId = 3,
                            EndDate = new DateTime(2022, 1, 10, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 2
                        },
                        new
                        {
                            TimeReportId = 6,
                            EmployeeId = 3,
                            EndDate = new DateTime(2022, 1, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 2
                        },
                        new
                        {
                            TimeReportId = 7,
                            EmployeeId = 4,
                            EndDate = new DateTime(2022, 1, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 2
                        },
                        new
                        {
                            TimeReportId = 8,
                            EmployeeId = 4,
                            EndDate = new DateTime(2022, 1, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 2
                        },
                        new
                        {
                            TimeReportId = 9,
                            EmployeeId = 5,
                            EndDate = new DateTime(2022, 1, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 17, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        },
                        new
                        {
                            TimeReportId = 10,
                            EmployeeId = 5,
                            EndDate = new DateTime(2022, 1, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        },
                        new
                        {
                            TimeReportId = 11,
                            EmployeeId = 5,
                            EndDate = new DateTime(2022, 1, 19, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        },
                        new
                        {
                            TimeReportId = 12,
                            EmployeeId = 5,
                            EndDate = new DateTime(2022, 1, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        },
                        new
                        {
                            TimeReportId = 13,
                            EmployeeId = 6,
                            EndDate = new DateTime(2022, 1, 18, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        },
                        new
                        {
                            TimeReportId = 14,
                            EmployeeId = 6,
                            EndDate = new DateTime(2022, 1, 19, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 19, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        },
                        new
                        {
                            TimeReportId = 15,
                            EmployeeId = 6,
                            EndDate = new DateTime(2022, 1, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 3
                        });
                });

            modelBuilder.Entity("APIProjekt.Models.Employee", b =>
                {
                    b.HasOne("APIProjekt.Models.Project", "Project")
                        .WithMany("Employee")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIProjekt.Models.TimeReport", b =>
                {
                    b.HasOne("APIProjekt.Models.Employee", "Employee")
                        .WithMany("TimeReport")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
